### ISSUE TITLE
crash when an app is installed

### ISSUE THREAD

**Issue by puschie286** [puschie286/fritzbox-bridge#4]
submitted report by user:
`/lib/logWrapper.js:63 this.ApiRegister[ID].put( '/addlog/', { log: message, group: 'fritz-bridge' } ) ^ TypeError: Cannot read property 'put' of null at Object.<anonymous> (/lib/logWrapper.js:63:27) at Object.<anonymous> (/lib/logWrapper.js:41:45) at ContextualLogger.invoke (/node_modules/js-logger/src/logger.js:118:5) at ContextualLogger.debug (/node_modules/js-logger/src/logger.js:88:9) at Object.debug (/node_modules/js-logger/src/logger.js:24:16) at Object.<anonymous> (/lib/logWrapper.js:125:10) at emitNone (events.js:106:13) at ApiApp.emit (events.js:208:7) at ManagerApps._onEvent (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/manager/apps.js:1:339) at _eventListeners.filter.forEach.t (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1220) at Array.forEach (<anonymous>) at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1197) at emitTwo (events.js:126:13) at process.emit (events.js:214:7) at emit (internal/child_process.js:762:12) at _combinedTickCallback (internal/process/next_tick.js:142:11)`

**Comment by puschie286** [comment]
added check for valid log function
update in >0.5.2
